version: "3"
services:
  tip-top:
    container_name: python-fingerprint-recognition
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - containers_network
    environment:
      - "VIRTUAL_HOST=test.com"
    expose:
      - 80

networks:
  containers_network:
    external: true
