version: "3"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: python_fingerprint_recognitionp_backend_local_django
    container_name: python_fingerprint_recognition
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "9000:8000"
    external_links:
      - postgres-dev:postgres
    networks:
      - containers_network
    environment:
      - "VIRTUAL_HOST=python-fingerprint-recognition.co"
    command: /start

networks:
  containers_network:
    external: true
